service: contact-form-lambda

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-south-1

functions:
  ContactFormFunction:
    handler: handler.contactFormHandler
    events:
      - http:
          path: /handle_form
          method: post
