service: static-site-mailer

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-south-1

functions:
  staticSiteMailer:
    handler: handler.contactFormHandler
    events:
      - http:
          method: post
          path: form_handler
          cors: true
